// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0MIgUH72HAgD6_yIZFKevinuS3nQXbQU',
    appId: '1:996876103970:web:201ba87fea3a0b41f3b57b',
    messagingSenderId: '996876103970',
    projectId: 'costing-master',
    authDomain: 'costing-master.firebaseapp.com',
    storageBucket: 'costing-master.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsutfUzqDvCSRenysfChrCayTU2bssSks',
    appId: '1:996876103970:android:2ff3642d2f2b2ce9f3b57b',
    messagingSenderId: '996876103970',
    projectId: 'costing-master',
    storageBucket: 'costing-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0RGaddmCJo2CLyFiK1YaXQkWRl94LDwA',
    appId: '1:996876103970:ios:46ec112e68b12f1ff3b57b',
    messagingSenderId: '996876103970',
    projectId: 'costing-master',
    storageBucket: 'costing-master.appspot.com',
    androidClientId: '996876103970-r207mu50mkkakja6tn98jrem2f1564fb.apps.googleusercontent.com',
    iosClientId: '996876103970-c76pmn7gu5b3beshl43nr2keml7iidmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.costingMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0RGaddmCJo2CLyFiK1YaXQkWRl94LDwA',
    appId: '1:996876103970:ios:46ec112e68b12f1ff3b57b',
    messagingSenderId: '996876103970',
    projectId: 'costing-master',
    storageBucket: 'costing-master.appspot.com',
    iosBundleId: 'com.example.costingMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0MIgUH72HAgD6_yIZFKevinuS3nQXbQU',
    appId: '1:996876103970:web:193ef2ba73183f54f3b57b',
    messagingSenderId: '996876103970',
    projectId: 'costing-master',
    authDomain: 'costing-master.firebaseapp.com',
    storageBucket: 'costing-master.appspot.com',
  );
}